#Data source configuration
spring:
  data:
    redis:
      ##redis Standalone environment configuration
      host: ${REDIS_HOST:192.168.60.76}
      port: ${REDIS_PORT:32576}
      database: 1
      password: ${REDIS_PASSWORD:redis@pass}
      ssl:
        enabled: false
      ##redis Cluster environment configuration
      #cluster:
      #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
      #  commandTimeout: 5000
  #excludeDruidDataSourceAutoConfigure
  datasource:
    # MySql Master data source information
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:192.168.60.75}:${DB_PORT:32433}/apaas_vlstream?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql@pass}
#Third party login
social:
  enabled: true
  domain: http://127.0.0.1:2888

#ossDefault configuration
oss:
  #turn onossConfiguration
  enabled: true
  #turn onosstype
  #minio、s3、qiniu、alioss、huaweiobs、tencentcos
  name: minio
  #Tenant model
  tenant-mode: true
  #ossService address
  endpoint: http://172.30.0.90:9000
  #ossTranslation service address, Used to change the return address to the converted external network address after uploading to the intranet
  #transform-endpoint: http://172.30.0.90:9000
  #accesskey
  access-key: bladexadmin
  #keykey
  secret-key: bladexadmin
  #bucket
  bucket-name: bladex

#bladeConfiguration
blade:
  #Distributed lock configuration
  lock:
    ##Whether to enable distributed locks
    enabled: true
    address: redis://${REDIS_HOST:192.168.60.76}:${REDIS_PORT:32576}
    password: ${REDIS_PASSWORD:redis@pass}
    database: 13
  token:
    #Tenant type configuration Single tenant or multi-tenant? single multi
    tenant-type: ${SSO_TENANT_TYPE:single}
    #Multi-tenant verificationtokenaddress
    multi-tenant-verify-token-address: ${SSO_MULTI_TENANT_VERIFY_TOKEN:http://apaas-sso.p-lvgemgroup/sso/v1/verifyToken}
    #Get multi-tenant user information
    multi-tenant-admin-user-url: ${GET_MULTI_TENANT_ADMIN_USER_URL:http://apaas-user.p-lvgemgroup/user/v1/userInfo}
    #Single tenant verificationtokenaddress
    single-tenant-verify-token-address: ${SSO_SINGLE_TENANT_VERIFY_TOKEN:http://oortcloud-sso.oort-apaas/sso/v1/verifyToken}
    #Get single tenant user information
    single-tenant-admin-user-url: ${GET_SINGLE_TENANT_ADMIN_USER_URL:http://oortcloud-sso.oort-apaas/sso/v1/getUserInfo}
